config/routes.rb
DNU::Application.routes.draw do
  devise_for :admins

  devise_for :users, :controllers => { :registrations => "registrations" }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'game_data' => 'game_data#index' , :as => 'game_data_index'
  namespace :game_data do resources :words,               :except => [:show, :destroy] end
  namespace :game_data do resources :effect_descriptions, :except => [:show, :destroy] end
  namespace :game_data do resources :event_descriptions,  :except => [:show, :destroy] end
  namespace :game_data do resources :battle_values,       :except => [:show, :destroy] end
  namespace :game_data do resources :elements,            :except => [:show, :destroy] end
  namespace :game_data do resources :diseases,            :except => [:show, :destroy] end
  namespace :game_data do resources :statuses,            :except => [:show, :destroy] end
  namespace :game_data do resources :item_types,          :except => [:show, :destroy] end
  namespace :game_data do resources :equip_types,         :except => [:show, :destroy] end
  namespace :game_data do resources :character_types,     :except => [:show, :destroy] end
  namespace :game_data do resources :landforms,           :except => [:show, :destroy] end
  namespace :game_data do resources :points,              :except => [:show, :destroy] end
  namespace :game_data do resources :point_uses,          :except => [:show, :destroy] end
  namespace :game_data do resources :serif_settings,      :except => [:show, :destroy] end
  namespace :game_data do resources :battle_types,        :except => [:show, :destroy] end
  namespace :game_data do resources :battle_settings,     :except => [:show, :destroy] end
  namespace :game_data do resources :art_types,           :except => [:show, :destroy] end
  namespace :game_data do resources :arts,                :except => [:show, :destroy] end
  namespace :game_data do resources :art_effects,         :except => [:show, :destroy] end
  namespace :game_data do resources :guardians,           :except => [:show, :destroy] end

  namespace :game_data do resources :maps,                :except => [:show, :destroy] end
  namespace :game_data do resources :equips,              :except => [:show, :destroy] end
  namespace :game_data do resources :sups,                :except => [:show, :destroy] end
  namespace :game_data do resources :traps,               :except => [:show, :destroy] end
  namespace :game_data do resources :skills,              :except => [:show, :destroy] end
  namespace :game_data do resources :item_skills,         :except => [:show, :destroy] end
  namespace :game_data do resources :item_uses,           :except => [:show, :destroy] end
  namespace :game_data do resources :items,               :except => [:show, :destroy] end
  namespace :game_data do resources :characters,          :except => [:show, :destroy] end
  namespace :game_data do resources :enemy_lists,         :except => [:show, :destroy] end
  namespace :game_data do resources :enemy_territories,   :except => [:show, :destroy] end
  namespace :game_data do resources :events,              :except => [:show, :destroy] end

  namespace :communication do resources :messages, :only => [ :index, :new, :create, :update ] end
  namespace :communication do resources :conversations end

  namespace :register do resources :mains    end
  namespace :register do resources :trades   end
  namespace :register do resources :products end

  namespace :register do resources :events, :except => [:index, :new, :destroy] end
  namespace :register do get ':event_content_id/events'     => 'events#index', :as => 'event_content_id_events'    end
  namespace :register do get ':event_content_id/events/new' => 'events#new',   :as => 'new_event_content_id_event' end

  namespace :register do resources :battles, :except => [:index, :new, :destroy] end
  namespace :register do get ':battle_type_id/battles'     => 'battles#index', :as => 'battle_type_id_battles'    end
  namespace :register do get ':battle_type_id/battles/new' => 'battles#new',   :as => 'new_battle_type_id_battle' end

  namespace :register do resources :pets, :except   => [:index, :new, :destroy]                    end
  namespace :register do get ':pet_id/pets'         => 'pets#index', :as => 'pet_id_pets'          end
  namespace :register do get ':pet_id/pets/new'     => 'pets#new',   :as => 'new_pet_id_pet'       end
  namespace :register do resources :skills, :except => [:index, :new, :destroy]                    end
  namespace :register do get ':skill_id/skills'     => 'skills#index', :as => 'skill_id_skills'    end
  namespace :register do get ':skill_id/skills/new' => 'skills#new',   :as => 'new_skill_id_skill' end
  namespace :register do resources :arts, :except   => [:index, :new, :destroy]                    end
  namespace :register do get ':art_id/arts'         => 'arts#index', :as => 'art_id_arts'          end
  namespace :register do get ':art_id/arts/new'     => 'arts#new',   :as => 'new_art_id_art'       end

  namespace :register do resources :messages,    :only => [ :show, :new, :create, :update ] end
  namespace :register do resources :communities, :only => [ :show, :new, :create, :update ] end
  namespace :register do resources :characters,  :only => [ :show, :new, :create, :update ] end
  namespace :register do resources :images,      :only => [ :show, :new, :create, :update ] end
  namespace :register do resources :initials,    :only => [ :show, :new, :create, :update ] end

  namespace :register do resources :makes, :only => [ :new, :create ] end

  scope ':room' do resources :chats, :only => [ :index, :create ] end

  get 'register' => 'register#index'  , :as => 'register_index'
  post 'history' => 'register#history', :as => 'register_history'

  get "result"                        => 'result#index',      :as => 'result'
  get "result/enos(/:new)"            => 'result#enos',       :as => 'result_enos'
  get "result/maps"                   => 'result#maps',       :as => 'result_maps'
  get "result(/:day)/eno/:id"         => 'result#eno',        :as => 'result_eno'
  get "result(/:day)/item/:id"        => 'result#item',       :as => 'result_item'
  get "result(/:day)/map/:name"       => 'result#map',        :as => 'result_map'
  get "result(/:day)/map/:name/:x/:y" => 'result#map_detail', :as => 'result_map_detail'
  get "result(/:day)/mapimage/:name"  => 'result#map_image' , :as => 'result_map_image'

  get  "gallery/:model(/:tag/tag)"   => 'gallery#index' , :as => 'gallerys'
  get  "gallery/:model/:id"          => 'gallery#show'  , :as => 'gallery'
  post "gallery/:model/:id"          => 'gallery#update'

  get 'ajax_img/:model(/:id)' => 'ajax#img',  :as => 'ajax_img'
  get 'ajax_user(/:id)'       => 'ajax#user', :as => 'ajax_user'
  get 'ajax_icon(/:id)'       => 'ajax#icon', :as => 'ajax_icon'

  get "helps(/:name)"           => 'help#index', :as => 'helps'
  get "help/:name"              => 'help#show' , :as => 'help'
  get "help/:model(/:id)/model" => 'help#model', :as => 'help_model'

  get  "tests/parse/:type(/:text)" => 'tests#parse', :as => 'tests_parse'
  post "tests/parse/:type(/:text)" => 'tests#parse', :as => 'tests_parse'
  get  "tests/document"
  get  "tests/message"
  get  "tests/battle"
  post "tests/battle"
  get  "tests/character"
  post "tests/character"
  get  "tests/skill"
  post "tests/skill"
  get  "tests/sup"
  post "tests/sup"
  get  "tests/art_effect"
  post "tests/art_effect"
  get  "tests/effects"
  post "tests/effects"

  get "kousin"      => 'home#kousin',      :as => 'kousin'
  get "saikousin"   => 'home#saikousin',   :as => 'saikousin'
  get "kousinstate" => 'home#kousinstate', :as => 'kousinstate'

  root :to => 'home#index'

end

app/models/register.rb
module Register
  def self.table_name_prefix
    'register_'
  end
end

app/models/register/art.rb
class Register::Art < ActiveRecord::Base
  belongs_to :user
  belongs_to :day
  belongs_to :art, :class_name => "GameData::Art"
  attr_accessible :art_id, :art_name_attributes, :art_pull_down_attributes, :art_lv_effects_attributes, :forges_attributes, :supplements_attributes, :hunts_attributes
  
  has_one :art_type,   :through => :art, :class_name => "GameData::ArtType"
  has_one :art_effect, :through => :art, :class_name => "GameData::ArtEffect"
  
  has_one  :art_name,       :dependent => :destroy
  has_one  :art_pull_down,  :dependent => :destroy
  has_many :art_lv_effects, :dependent => :destroy
  has_many :forges,         :order => "id ASC", :dependent => :destroy, :as => :productable
  has_many :supplements,    :order => "id ASC", :dependent => :destroy, :as => :productable
  has_many :hunts,          :order => "id ASC", :dependent => :destroy, :as => :productable
  
  accepts_nested_attributes_for :art_name, :reject_if => :all_blank
  accepts_nested_attributes_for :art_pull_down
  accepts_nested_attributes_for :art_lv_effects
  accepts_nested_attributes_for :forges,      :reject_if => proc { |attributes| attributes.all?{|k,v| [:art_effect_id, :item_type_index, :experiment].include?(k.to_sym) ? true : v.blank?} }
  accepts_nested_attributes_for :supplements, :reject_if => proc { |attributes| attributes.all?{|k,v| [:art_effect_id, :experiment].include?(k.to_sym) ? true : v.blank?} }
  accepts_nested_attributes_for :hunts,       :reject_if => proc { |attributes| attributes.all?{|k,v| [:art_effect_id].include?(k.to_sym) ? true : v.blank?} }
  
  def build_art
    self.build_art_name if self.art_name.nil? and self.art_type.try(:rename)
    if has_pull_down?
      self.build_art_pull_down if self.art_pull_down.nil?
    end
    lvs.each do |lv|
      unless self.art_lv_effects.where(:lv => lv).exists?
        self.art_lv_effects.build(:lv => lv)
      end
    end
    [:forge, :supplement, :hunt].each do |type|
      product_count(type).times do
        self.send(type.to_s.pluralize).build(:art_effect_id => self.art_effect.id)
      end
    end
  end
  
  def product_count(type)
    if self.art_effect.present?
      self.art_effect.tree[:"#{type}able_number"].to_i-self.send(type.to_s.pluralize).where(:art_effect_id => self.art_effect.id).count
    else
      0
    end
  end
  
  def hunt_list(kinds)
    user.hunt_list(kinds, day.nil? ? Day.last_day_i : day.day-1)
  end
  
  def pull_down
    self.art_pull_down.try(:pull_down)
  end
  
  def off_lvs
    self.art_lv_effects.where(:setting => false).pluck(:lv)
  end
  
  def definitions
    if self.art_effect.present?
      @definitions ||= self.art_effect.tree[:definitions]
    else
      @definitions ||=[]
    end
  end
  
  def has_pull_down?
    pull_downs.present?
  end
  
  def pull_downs
    @pull_downs ||= definitions.find_all{|h| h[:pull_down].present? and h[:lv].to_i <= art_lv}.inject({}){ |h,v| h.tap{ h["LV#{v[:lv]}：#{v[:pull_down]}"] = v[:pull_down] } }
  end
  
  def lv_effects
    @lv_effects ||= definitions.find_all{|h| h[:pull_down].nil?     and h[:lv].to_i <= art_lv}.inject({}){ |h,v| h.tap{ h[v[:lv].to_i] = v[:caption] } }
  end
  
  def lvs
    @lvs ||= lv_effects.keys
  end
  
  def name
    art.name
  end
  
  def caption
    art.caption
  end
  
  def art_lv
    @art_lv ||= user.result(:art).where(:art_id => self.art_id).first.lv.to_i
  end
end

app/models/register/art_lv_effect.rb
class Register::ArtLvEffect < ActiveRecord::Base
  belongs_to :art
  attr_accessible :lv, :setting
  
  validates :lv,      :numericality => { :only_integer => true, :greater_than => 0 }
  validates :setting, :inclusion => { :in => [true, false] }
end

app/models/register/art_name.rb
class Register::ArtName < ActiveRecord::Base
  belongs_to :art
  attr_accessible :caption, :name
  
  has_one :user, :through => :art
  
  validates :name,    :length => { :maximum => Settings.maximum.name, :tokenizer => DNU::Text.counter(:string) }
  validates :caption, :length => { :maximum => Settings.maximum.caption, :tokenizer => DNU::Text.counter(:document) }
  
  dnu_string_html   :name
  dnu_document_html :caption
  
  def character_active
    user
  end
  
  def character_passive
    user
  end
end

app/models/register/art_pull_down.rb
class Register::ArtPullDown < ActiveRecord::Base
  belongs_to :art
  attr_accessible :pull_down
end

app/models/register/battle.rb
class Register::Battle < ActiveRecord::Base
  belongs_to :user
  belongs_to :day
  belongs_to :battle_type, :class_name => "GameData::BattleType"
  attr_accessible :battle_type_id, :equips_attributes, :battle_settings_attributes, :serif_settings_attributes, :item_skill_settings_attributes
  
  has_many :equips,              :dependent => :destroy, :as => :battlable
  has_many :battle_settings,     :order => "priority ASC", :dependent => :destroy, :as => :battlable
  has_many :serif_settings,      :dependent => :destroy, :as => :battlable
  has_many :item_skill_settings, :order => "priority ASC", :dependent => :destroy, :as => :battlable
  
  accepts_nested_attributes_for :equips,              :reject_if => proc { |attributes| attributes.all? {|k,v| [:kind].include?(k.to_sym) ? true : v.blank?} }
  accepts_nested_attributes_for :battle_settings,     :reject_if => :no_change_from_default
  accepts_nested_attributes_for :serif_settings,      :reject_if => proc { |attributes| attributes.all? {|k,v| [:serif_setting_id].include?(k.to_sym) ? true : v.blank?} }
  accepts_nested_attributes_for :item_skill_settings, :reject_if => :no_change_from_default
  
  validates :battle_type, :presence => true
  
  def learned_skills
    @learned_skills ||= user.result(:skill, (day.try(:day) || Day.last_day_i)).inject({}){ |h,r| h.tap{ h["#{r.name} 消費#{r.cost}"] = r.skill.id } }
  end
  
  def build_battle
    (8-self.battle_settings.size).times{self.battle_settings.build}
    (8-self.serif_settings.size).times{self.serif_settings.build}
    (1-self.item_skill_settings.size).times{self.item_skill_settings.build}
    
    kinds = GameData::EquipType.pluck(:name)
    kinds.each do |kind|
      self.equips.build(:kind => kind) unless self.equips.exists?(:kind => kind)
    end
    self.equips.sort_by!{|r| kinds.index(r.kind) }
  end
  
  private
  def no_change_from_default(row)
    # priorityとuse_conditionとfrequency以外が全てブランクの場合リジェクト
    row.all?{ |k,v| [:priority, :use_condition_id, :frequency_id].include?(k.to_sym) ? true : v.blank? }
  end
  
end

app/models/register/battle_setting.rb
class Register::BattleSetting < ActiveRecord::Base
  belongs_to :battlable,     :polymorphic => true
  belongs_to :skill,         :class_name => "GameData::Skill"
  belongs_to :use_condition, :class_name => "GameData::BattleSetting"
  belongs_to :frequency,     :class_name => "GameData::BattleSetting"
  belongs_to :target,        :class_name => "GameData::BattleSetting"
  
  attr_accessible :skill_id, :frequency_id, :message, :priority, :target_id, :target_variable, :use_condition_id, :use_condition_variable, :condition
  serialize :condition
  
  validates :skill,         :presence => true
  validates :priority,      :numericality => { :only_integer => true, :greater_than => 0 }
  validates :use_condition, :presence => true
  validates :frequency,     :presence => true
  validates :condition,     :presence => true
  validates :message,       :length => { :maximum => Settings.maximum.message, :tokenizer => DNU::Text.counter(:message) }
  
  dnu_message_html  :message
  before_validation :set_condition
  
  def user
    battlable.try(:user)
  end
  
  def day
    battlable.try(:day)
  end
  
  def character_active
    user
  end
  
  def character_passive
  end
  
  def tree
    @tree ||= {
      :skill => {
        :name      => skill.name,
        :priority  => priority,
      }.merge(condition)
    }
  end
  
  def use_conditions
    @use_conditions ||= GameData::BattleSetting.select([:id,:name]).find_all_by_kind('使用条件').inject({}){ |h,r| h.tap{ h[r.name] = r.id } }
  end
  
  def frequencies
    @frequencies ||= GameData::BattleSetting.select([:id,:name]).find_all_by_kind('使用頻度').inject({}){ |h,r| h.tap{ h[r.name] = r.id } }
  end
  
  def targets
    @targets ||= GameData::BattleSetting.select([:id,:name]).find_all_by_kind('対象指定').inject({}){ |h,r| h.tap{ h[r.name] = r.id } }
  end
  
  def selected_frequency
    @selected_frequency ||= GameData::BattleSetting.select(:id).find_by_name('頻度5').id
  end
  
  def selected_use_condition
    @selected_use_condition ||= GameData::BattleSetting.select(:id).find_by_name('通常時').id
  end
  
  private
  def set_condition
    skill_condition = DNU::Data.parse(:skill_condition, "#{self.use_condition.name} #{self.frequency.name}")
    if skill_condition.present?
      self.condition = set_condition_tree(skill_condition)
    else
      errors.add(:condition, :invalid)
    end
  end
  
  def set_condition_tree(tree)
    case tree
    when Hash
      tree.inject({}){ |h,(k,v)|
        h.tap{
          if k == :variable
            if v[:name].to_sym == :A
              h[:fixnum] = self.use_condition_variable
            else
              h[:fixnum] = self.target_variable
            end
          else
            h[k] = set_condition_tree(v)
          end
        }
      }
    when Array
      tree.map{ |v| set_condition_tree(v) }
    else
      tree
    end
  end
end

app/models/register/blossom.rb
class Register::Blossom < ActiveRecord::Base
  belongs_to :main
  belongs_to :train, :class_name => "GameData::Train"
  attr_accessible :train_id
  
  validates :train, :presence => true
end

app/models/register/community.rb
class Register::Community < ActiveRecord::Base
  belongs_to :user
  belongs_to :day
  
  def build_community
  end
end

app/models/register/dispose.rb
class Register::Dispose < ActiveRecord::Base
  belongs_to :main
  attr_accessible :number
  
  has_one :day,  :through => :main
  has_one :user, :through => :main
  
  validates :number, :numericality => { :only_integer => true, :greater_than => 0 }
end

app/views/register/products/_form.html.haml
= simple_form_for(register_product) do |form_product|
  = register_product.updated_at.try(:to_s, :jp)
  = render 'register/error',  { :register_error   => register_product }
  = render 'form_product_permission', { :register_product => register_product, :form_product => form_product }
  = render 'form_forge',              { :register_product => register_product, :form_product => form_product }
  = render 'form_supplement',         { :register_product => register_product, :form_product => form_product }
  = render 'form_hunt',               { :register_product => register_product, :form_product => form_product }
  - unless @read_only
    .actions
      %button.btn.btn-large.btn-warning{"data-remote" => "true"} 確認する
      = form_product.submit :class => "btn btn-large btn-success"
  - if @update_time
    .actions
      = form_product.submit :class => "btn btn-large btn-warning"

app/views/register/products/_form_forge.html.haml
%br
= form_product.simple_fields_for :forges, :wrapper => :simple, :defaults => { :as => (:plain if @read_only), :user => current_user, :input_html => { :class => :'span2' } } do |form_forge|
  = form_forge.input :art_effect_id, :as => :hidden
  = form_forge.input :user_id, :as => :eno, :read_only => @read_only
  の
  = form_forge.input :number, :as => :item_number, :eno => form_forge.object.user_id, :read_only => @read_only
  を使って
  - if form_forge.object.art_effect.forgeable_item_types.count == 1
    = form_forge.object.art_effect.forgeable_item_types.keys.first
    = form_forge.input :item_type_index, :as => :hidden, :input_html => { :value => form_forge.object.art_effect.forgeable_item_types.values.first }
  - else
    = form_forge.input :item_type_index, :collection => form_forge.object.art_effect.forgeable_item_types
  を
  = form_forge.input :experiment, :collection => { "作製" => false,  "作製実験" => true }, :include_blank => false
  = form_forge.input :name, :wrapper => :bootstrap, :input_html => { :class => :'string-editor span6' }
  = form_forge.input :caption, :wrapper => :bootstrap, :input_html => { :class => :'document-editor span9', :rows => 2 }
  = form_forge.input :message, :wrapper => :bootstrap, :input_html => { :class => :'message-editor span9', :rows => 2 }
  %br

app/views/register/products/_form_hunt.html.haml
%br
= form_product.simple_fields_for :hunts, :wrapper => :simple, :defaults => { :as => (:plain if @read_only), :user => current_user, :input_html => { :class => :'span4' } } do |form_hunt|
  - if register_product.hunt_list(form_hunt.object.art_effect.tree[:huntable_character_types]).present?
    = form_hunt.input :art_effect_id, :as => :hidden
    = form_hunt.input :party_member_id, :collection => register_product.hunt_list(form_hunt.object.art_effect.tree[:huntable_character_types])
    を狩猟
    = form_hunt.input :message, :wrapper => :bootstrap, :input_html => { :class => :'message-editor span9', :rows => 2 }, :wrapper_html => { :class => :clearfix }
    %br

app/views/register/products/_form_product_permission.html.haml
%br
= form_product.label :product_permission
= form_product.simple_fields_for :product_permissions, :wrapper => :simple, :defaults => { :user => current_user, :input_html => { :class => :'span2' } } do |form_product_permission|
  = form_product_permission.input :user_id, :as => :eno, :read_only => @read_only
%br
%br

app/views/register/products/_form_supplement.html.haml
%br
= form_product.simple_fields_for :supplements, :wrapper => :simple, :defaults => { :as => (:plain if @read_only), :user => current_user, :input_html => { :class => :'span2' } } do |form_supplement|
  = form_supplement.input :art_effect_id, :as => :hidden
  = form_supplement.input :user_id, :as => :eno, :read_only => @read_only
  の
  = form_supplement.input :material_number, :as => :item_number, :eno => form_supplement.object.user_id, :read_only => @read_only
  を使って
  = form_supplement.input :item_number, :as => :item_number, :eno => form_supplement.object.user_id, :read_only => @read_only
  に
  = form_supplement.input :experiment, :collection => { "付加" => false,  "付加実験" => true }, :include_blank => false
  %br
  = form_supplement.input :message, :wrapper => :bootstrap, :input_html => { :class => :'message-editor span9', :rows => 2 }, :wrapper_html => { :class => :clearfix }
  %br

app/views/register/products/edit.html.haml
%h1= @register_product.class.model_name.human.downcase
= render 'form', { :register_product => @register_product }

= link_to 'Show', @register_product
|
= link_to 'Back', register_products_path

app/views/register/products/index.html.haml
%h1= @register_products.first.class.model_name.human.downcase
- @register_products.each do |register_product|
  .alert
    - if register_product.day.present?
      %span.badge.badge-important #{register_product.day.day}日
    = render 'form', { :register_product => register_product }
    = link_to 'Show', register_product
= paginate @register_products

app/views/register/products/new.html.haml
%h1= @register_product.class.model_name.human.downcase
= render 'form', { :register_product => @register_product }

app/views/register/products/show.html.haml
%h1= @register_product.class.model_name.human.downcase
= render 'form', { :register_product => @register_product }

= link_to 'Edit', edit_register_product_path
|
= link_to 'Back', register_products_path